name: Dependency Track Submission

on:
  push:
    branches:
      - main

jobs:
  trivy-sbom-and-dependencytrack-upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Create sbom with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          output: sbom.cdx.json
      - name: Upload sbom to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: ${{ secrets.DEPENDENCYTRACK_HOSTNAME }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          projectName: ${{ github.repository }}
          projectVersion: ${{ github.ref_name }}
          bomFilename: "sbom.cdx.json"
          parent: ${{ secrets.DEPENDENCYTRACK_PARENT_UUID }}
          autoCreate: true