name: Dependency Track Submission

on:
  workflow_call:
  push:
    branches:
      - chore/pln-1878/integrate-dependency-track-adjustments

jobs:
  dependency-track:
    uses: conology/devops-workflows/.github/workflows/trivy-dptrack.yml@main
    with:
      project-name: ${{ github.repository }}
      project-version: ${{ github.ref_name }}
      parent: 7fa5716d-ef4b-4739-9744-ddee01113cb5
    secrets: inherit